import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <div
            className="w-[90%] py-4  mx-auto mt-14 flex justify-center">
            <p className="font-medium  font-chat">
                * Disclaimer: The responses are generated by an AI.
            </p>
        </div>
    );
};

export default Disclaimer;